spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
kis:
  base-url: https://openapivts.koreainvestment.com:29443
  app-key: PSLB72T1zvI2fQrJIulELY9axGlRC5aBndFk
  app-secret: MDRuRWK/y1AwbQIdHTywOsQPxTsXm0hl/FlDYYOrunC38Ob1HP810jQub3jrTwOFeX/bIspJ5j2MgO36PLBiNLJ7FPYSXAjkc82y4mUbhEmOMlREJl95CxkeuMRHKrKzIQnjbTxBNqUq/xWISWbs7bYr0o23YOIDru0nHi/ZeJ3jaBerzSs=
