spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stockport-db.cb4iuaiky995.ap-northeast-2.rds.amazonaws.com:3306/stockport?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: 'admin'
    password: 'shwjddbs1!'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always

kis:
  base-url: https://openapivts.koreainvestment.com:29443
  app-key: PSLB72T1zvI2fQrJIulELY9axGlRC5aBndFk
  app-secret: MDRuRWK/y1AwbQIdHTywOsQPxTsXm0hl/FlDYYOrunC38Ob1HP810jQub3jrTwOFeX/bIspJ5j2MgO36PLBiNLJ7FPYSXAjkc82y4mUbhEmOMlREJl95CxkeuMRHKrKzIQnjbTxBNqUq/xWISWbs7bYr0o23YOIDru0nHi/ZeJ3jaBerzSs=

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000